version: "3.4"

services:
  app:
    image: santuu-front
    command: "tail -f /dev/null"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app"
    # network_mode: "host"
